url: https://rawajit.com


# Site settings
title: RAWAJ ALITQAN for IT
email: mirsal@rawajit.com



# Tracker
analytics:
# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
permalink: /:title/

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

