url: https://rawajit.com


# Site settings
title: شركة رواج الإتقان لتقنية المعلومات
description: مهندسين متخصصين ومتفرغين لتطويع أحدث التقنيات لخدمتك 
email: mirsal@rawajit.com
social:
  - title: linkedin
    url: https://www.linkedin.com/company/rawaj-it
  - title: twitter
    url: https://twitter.com/rawaj_it
  - title: facebook
    url: https://www.facebook.com/rawaj.information.technology
  - title: instagram
    url: https://www.instagram.com/rawaj_it/
  - title: tiktok
    url: https://www.tiktok.com/@rawaj_it
  - title: youtube
    url: https://www.youtube.com/@rawajit
author:  رواج الإتقان لتقنية المعلومات # add your name
author-img: RIIT.png # add your photo
about-author:  مهندسين متخصصين ومتفرغين لتطويع أحدث التقنيات لخدمتك # add description
social-twitter: rawaj_it
social-facebook: rawaj.information.technology
social-instagram: rawaj_it
social-email: mirsal@rawajit.com

# Tracker
analytics:
# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
permalink: /:title/

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

